### ISSUE TITLE
Deleting kafka dir yields an exception

### ISSUE THREAD

**Issue by bai** [coreos/zetcd#72] opened 2017-07-06 06:18 UTC
When using `zkCli` to delete kafka chroot dir, getting an error:

```
[zk: zetcd(CONNECTED) 1] rmr /kafka
Node not empty: /kafka/brokers/ids

[zk: zetcd(CONNECTED) 2] ls /kafka/brokers/ids 
[]
```

However, as you see the node is empty. When doing the same operation with native zookeeper things work as expected.

From zetcd logs:

```
I0706 06:15:54.018151       1 zketcd.go:439] GetChildren(10) = (zxid=285, resp={Children:[]})
I0706 06:15:54.018189       1 conn.go:139] conn.Send(xid=10, zxid=284, &{Children:[]})
I0706 06:15:54.019391       1 server.go:110] zkreq={xid:11 req:*zetcd.DeleteRequest:&{Path:/kafka/brokers/ids Version:-1}}
I0706 06:15:54.019424       1 zklog.go:33] Delete(11,{Path:/kafka/brokers/ids Version:-1})
I0706 06:15:54.026331       1 conn.go:139] conn.Send(xid=11, zxid=285, 0xc420200110)
```

Zk Client version:

```
Client environment:zookeeper.version=3.4.9-1757313, built on 08/23/2016 06:50 GMT
```

**Comment by heyitsanthony** [comment] 2017-08-08 23:15
tested in #76, cannot reproduce; likely fixed by #77. Closing

**Closed by heyitsanthony** 2017-08-08 23:15 UTC
Labels: apps, bug
